### ISSUE TITLE
Auto scroll to particular time in day view

### ISSUE THREAD

**Issue by viklele** [twinssbc/Ionic2-Calendar#55]
Is there  a way to force the day view to scroll to particular time initially? At present the view always shows the event list from 12AM. Can it be made to automatically scroll to the hour nearest to current time (the way it is done in native calendar in android)?

More often than not, users are interested in viewing the up coming events for today, and default display from 12AM means they are almost always forced to scroll.

Regards,
Vikram

**Comment by twinssbc** [comment]
@viklele The source code needs to be modified to achieve your requirement. IMO, it is not a general requirement, although I admit it is probably more user friendly. So I won't expose such option in the short term.

**Comment by ruileal** [comment]
I agree that this behaviour, more than user friendly, can sometimes be a requirement. Ot at least having an option to have this time autoscroll. For example, if the application is for a 9h-17h business, the user should not be looking at the first hours from midnight.
@twinssbc if source code change is not possible for now, do you see any way to have it set in the component using ionic2-calendar to auto-scroll to a target time div?
Thanks in advance,
Rui

**Comment by twinssbc** [comment]
@viklele @ruileal I have added two scrolling related options, **scrollToHour** and **preserveScrollPosition**, you could get more information from README.
Feel free to have a try.

**Comment by viklele** [comment]
Thanks.

Will try it and revert with my feedback.

Regards
Vikram

**Comment by VinuthaShreyas** [comment]
I tries using the scrollToHour both in the HTML in the calendar config.
Also tried using in the component by setting calendar
{
  mode: 'day',
        currentDate: new Date(),
        scrollToHour: 9
}
Both the solution seems to be not working

**Comment by twinssbc** [comment]
@VinuthaShreyas 
If you set scrollToHour as below in your component ts file
```
calendar = {
mode: 'day',
currentDate: new Date(),
scrollToHour: 9
}
```

You could use it in your component HTML file as below
```
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            [scrollToHour]="calendar.scrollToHour"
...
  ></calendar>
```

**Comment by VinuthaShreyas** [comment]
I tried all this. Nothing seems to be working. I am using ionic4. Could this be an issue?

**Comment by twinssbc** [comment]
@VinuthaShreyas "Not working" means the scroll bar doesn't scroll at all when you swipe to next week?

**Comment by VinuthaShreyas** [comment]
I want the scroll to work in the dayview calendar

**Comment by twinssbc** [comment]
@VinuthaShreyas It should work. Does it work in week view? Maybe a screenshot or video clip could help.

**Comment by VinuthaShreyas** [comment]
Actually I have two calendar instances on the same page. One for the month view. Beneath i have the day view.

I have configured events in such a way when a day changes on the month view , the corresponding event loads in the day view. This all works perfectly fine.

I am setting the scrollTohour property for the day view.Following is the code snippet
  <calendar [eventSource]="eventSourceforMonth" [calendarMode]="calendarMonthView.mode"
        (onCurrentDateChanged)="onCurrentDateChangedMonth($event)"       
    </calendar>

    <ng-template #template let-displayEvent="displayEvent">
       --------
    </ng-template>

    <calendar [dayviewNormalEventTemplate]="template" [eventSource]="eventSourceforDay"
        [calendarMode]="calendarDayView.mode" (onTimeSelected)="onTimeSelectedDay($event)" **[scrollToHour]="calendarDayView.scrollToHour"
        [preserveScrollPosition]="calendarDayView.preserveScrollPosition"**
         formatHourColumn="hh:mma" 
    </calendar>


Component code

 calendarMonthView = {
        mode: 'month',
        currentDate: new Date()
    };

    calendarDayView = {
        mode: 'day',
        currentDate: new Date(),
        scrollToHour: 9,
        preserveScrollPosition: true
    };

**Comment by twinssbc** [comment]
@VinuthaShreyas I tried putting two calendars in the same page and the second one has scrollToHour set to 9. It is working, although it may not scroll to 9AM, because of the page height limitation. Is preserveScrollPosition option working?

**Comment by VinuthaShreyas** [comment]
@twinssbc 
I agree with you when there are two calendars on the same page,scrolling may be a challenge considering the height limitation.

But scrollToHour doesn't work even when I put the single instance of the day view calendar on the page
commenting the other instance

**Comment by twinssbc** [comment]
@VinuthaShreyas Could you provide your entire HTML and ts files?

**Comment by radious15** [comment]
Hello!

I have a small issue with scrolling as well, it only works when I am changing the mode from week to day or the contrary, not on the first display of the calendar.  However PreserveScroll works perfectly.

Any idea?

Thanks you very much!!

BR,
Radious

**Comment by twinssbc** [comment]
@radious15 This looks like a bug. I will fix it.

**Comment by radious15** [comment]
@twinssbc thanks !

**Comment by twinssbc** [comment]
@radious15 I have fixed it in version 0.5.5. Feel free to have a try.

**Comment by radious15** [comment]
@twinssbc thanks!

Unfortunately, it doesn't work on first opening of the calendar after updating to 0.5.5:

- I open the calendar for the first time, it doesn't scroll.
- I close the calendar, open it again and it works.

My code is as follow:

```
calendar = {
    mode: 'week',
    scrollToHour: 9,
    currentDate: new Date(),
    startHour: "00",
    endHour: "24",
    step: "30",
    startingDayWeek: "1",
    formatHourColumn: "HH:mm",
  };
```

```
 <calendar [eventSource]="this.eventList"  [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate" (onCurrentDateChanged)="onCurrentDateChanged($event)"
    (onEventSelected)="openEventModal($event)" (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)" [formatHourColumn]="calendar.formatHourColumn"
    [startHour]="calendar.startHour" [endHour]="calendar.endHour" [step]="calendar.step"
    [startingDayWeek]="calendar.startingDayWeek" [sliderOptions]="calendar.sliderOptions" [lockSwipes]="true"
    [dayviewNormalEventSectionTemplate]="dayNormalSectionTemplate" [dayviewNormalEventTemplate]="dayNormalTemplate"
    preserveScrollPosition=true [scrollToHour]="calendar.scrollToHour" [weekviewNormalEventSectionTemplate]="templateWeekViewSectionTemplate"
    [weekviewNormalEventTemplate]="templateWeekViewTemplate" [weekviewHeaderTemplate]="templateeWeekViewHeader">
  </calendar>
```

Thanks for your kind help!

BR,
Radious

**Comment by twinssbc** [comment]
@radious15 You mentioned you close the calendar and open it again. When do you put the calendar? In  a modal dialog?

**Comment by radious15** [comment]
@twinssbc yes, I put the calendar in a modal dialog. Do you have any idea what causes the issue? Thank you very much!

**Comment by twinssbc** [comment]
@radious15 I think it's due to the modal dialog hasn't been fully rendered, but the calendar tries to scroll to the init position. I slightly adjust the delay time, it's working in my test project now. Could you try the latest version 0.5.6?

**Comment by radious15** [comment]
@twinssbc I tried, and it still doesn't scroll on first opening. Any guess? I tried changing my html with less customization but it didn't change anything. Thank you!

**Comment by twinssbc** [comment]
@radious15 Could you provide your source code?

**Comment by radious15** [comment]
@twinssbc I tried to reproduce it on stackblitz, but at the moment I upgrade the calendar to 0.5.6 I get the error "Error in /turbo_modules/@ionic/angular@4.10.0/dist/fesm5.cjs.js (942:54)
i0.defineInjectable is not a function"

**Comment by radious15** [comment]
@twinssbc I tried a light version on my code, I still have the issue:

**Calendar-test.html**

`<ion-content>
  <calendar [eventSource]="this.eventList" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate"
    [formatHourColumn]="calendar.formatHourColumn" [startHour]="calendar.startHour" [endHour]="calendar.endHour"
    [step]="calendar.step" [startingDayWeek]="calendar.startingDayWeek" [sliderOptions]="calendar.sliderOptions"
    [lockSwipes]="true" [scrollToHour]="calendar.scrollToHour" preserveScrollPosition=false>
  </calendar>
</ion-content>`

**Calendar-test.ts**

```
import { Component, OnInit, ViewChild, Inject, LOCALE_ID, Input } from '@angular/core';
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { ModalController } from '@ionic/angular';

@Component({
  selector: 'app-calendar-test',
  templateUrl: './calendar-test.page.html',
  styleUrls: ['./calendar-test.page.scss']

})
export class CalendarTestPage implements OnInit {
  @ViewChild(CalendarComponent, { static: true }) myCal: CalendarComponent;

  viewTitle: String; // Title
  calendar = {
    mode: 'week',
    scrollToHour: 9,
    currentDate: new Date(),
    startHour: "00",
    endHour: "24",
    step: "30",
    startingDayWeek: "1",
    formatHourColumn: "HH:mm",
    sliderOptions: {
      speed: 300,
      effect: "slide"
    }
  };

  eventList: Array<any> = []; // List of event displayed

  constructor(private modalController: ModalController) { }

  ngOnInit() { }

  closeModal() {
    this.modalController.dismiss("cancel");
  }

}
```

**Home.ts (open calendar modal)**
```

async openCalendarAdminModal() {

    const modal = await this.modalController.create({
      component: CalendarTestPage,
    });

    modal.onDidDismiss().then(data => {
      console.log("CLOSED CALENDAR");
    });
    modal.present();
  }`
```

**The result on first opening:**

![calendar-first-opening-scroll-ko](https://user-images.githubusercontent.com/44028371/66267595-ffda0d80-e832-11e9-84bb-9e299562b353.png)

**The result on second opening:**

![calendar-second-opening-scroll-ok](https://user-images.githubusercontent.com/44028371/66267596-0072a400-e833-11e9-8461-fb891483478b.png)

Thanks for your help!

**Comment by radious15** [comment]
Hi @twinssbc , did you manage to reproduce the issue? Thank you very much!!!

**Comment by twinssbc** [comment]
@radious15 Yes, cannot always reproduce, I guess still the timing issue. I published a new version, 0.5.7 which further increase the interval. Feel free to give a try.

**Comment by radious15** [comment]
Hi @twinssbc , unfortunately I still have the same issue. It does not scroll on first opening of the modal, only on the second opening. I also changed the modal to a push navigation, and got the same issue. I used the version 0.5.7, and the same simple code that I posted above. Also, if I have two calendars on two different pages, I can open the first one and it doesn't scroll, but if I open the second one for the first time then it does. Thanks for your kind help!

**Comment by radious15** [comment]
@twinssbc I changed the modal to a push navigation, and unfortunately I have the same issue. I use the version 0.5.7, and the same simple code that I posted above. It is the same behavior: doesn't scroll on first opening, only on second. Thanks for your kind help!

**Comment by radious15** [comment]
@twinssbc I investigated, if I remove the "preserveScrollPosition" variable, it doesn't scroll when I open the calendar for the second time. Sorry for spamming!

**Comment by radious15** [comment]
Hi @twinssbc , I set 400 on the setTimeOut and it works for me. As I am anyway retrieving the events from a DB, I have a loading screen set as an overlay on the calendar. So on the first opening, I block my "loading" event to minimum 400, it's not much an issue.  I investigated the problem and it is very hard (even maybe impossible) to find, seems like there is nothing we can do about it anyway. Thanks a lot for your great help! I have a new ticket coming for you... :) (Regarding the slider for which I would love a small fix). Have a nice evening!

**Comment by tschonner** [comment]
<img width="456" alt="Github Change Inputtime" src="https://user-images.githubusercontent.com/57210611/67926078-61cd2f00-fbb5-11e9-8c83-afaec9d567c9.PNG">
Hi @twinssbc, it is possible to bind the scrollToHour option for example to an input type time, so if you change its value, it will scroll to the current input time in day view. Unfortunately it only works, after you changed between day and week view. Is it possible to scroll automatically to the selected time, without changing the calendar mode manually?

Thanks in advance,
Johannes

**Comment by twinssbc** [comment]
@twinssbc Unfortunately, scrollToHour option doesn't support changing value dynamically. I think you could probably use some native DOM selector to find the weekview element and scroll its position.

**Comment by tschonner** [comment]
@twinssbc It's working perfectly. Thank you very much for you advice.
